#!/bin/bash
# Auto-install user-level Claude skills on session start (Claude Code on the web).
# The container is ephemeral, so anything in ~/.claude/skills doesn't survive
# between sessions. This hook restores them.
set -euo pipefail

# Only run on remote (web) sessions — local installs are managed by the user.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

# ---------------------------------------------------------------------------
# 1) agentmemory (jayzeng/agentmemory) — persistent memory CLI + skill.
# ---------------------------------------------------------------------------
AM_SHIM="$HOME/.local/bin/agent-memory"
AM_SKILL="$HOME/.claude/skills/agent-memory/SKILL.md"
AM_PKG_DIR="/opt/node22/lib/node_modules/myagentmemory"
AM_CLI_JS="$AM_PKG_DIR/dist/cli.js"

if [ -f "$AM_SKILL" ] && [ -x "$AM_SHIM" ] && [ -f "$AM_CLI_JS" ] && [ -d "$HOME/.agent-memory" ]; then
  echo "agentmemory: already installed, skipping"
else
  echo "agentmemory: installing..."
  if [ ! -f "$AM_CLI_JS" ]; then
    npm install -g myagentmemory >/dev/null 2>&1
  fi
  # Bundled installer drops the SKILL.md and an ~/.local/bin symlink to the
  # prebuilt Mac arm64 binary (broken on Linux). We replace that with a Node shim.
  bash "$AM_PKG_DIR/scripts/install-skills.sh" >/dev/null 2>&1 || true
  mkdir -p "$HOME/.local/bin"
  rm -f "$AM_SHIM"
  cat > "$AM_SHIM" <<'SHIM_EOF'
#!/usr/bin/env bash
exec node /opt/node22/lib/node_modules/myagentmemory/dist/cli.js "$@"
SHIM_EOF
  chmod +x "$AM_SHIM"
  ln -sf "$AM_SHIM" /opt/node22/bin/agent-memory 2>/dev/null || true
  if [ ! -d "$HOME/.agent-memory" ]; then
    "$AM_SHIM" init >/dev/null 2>&1 || true
  fi
  echo "agentmemory: ready"
fi

# ---------------------------------------------------------------------------
# 2) mattpocock/skills — engineering & productivity skill pack (14 skills).
#    Uses the `skills` CLI (vercel-labs) to install globally for claude-code.
#    Marker: presence of the `diagnose` skill (first skill alphabetically).
# ---------------------------------------------------------------------------
MP_MARKER="$HOME/.claude/skills/diagnose/SKILL.md"

if [ -f "$MP_MARKER" ]; then
  echo "mattpocock/skills: already installed, skipping"
else
  echo "mattpocock/skills: installing..."
  npx -y skills@latest add mattpocock/skills -g -a claude-code -s '*' -y >/dev/null 2>&1 || \
    echo "mattpocock/skills: install failed (continuing)"
  if [ -f "$MP_MARKER" ]; then
    echo "mattpocock/skills: ready"
  fi
fi

# ---------------------------------------------------------------------------
# 3) nuwa-skill (alchaincyf/nuwa-skill) — 女娲: distills a person / thinking
#    style into a runnable persona Skill. Installs the single `huashu-nuwa`
#    skill. Marker: presence of that skill's SKILL.md.
# ---------------------------------------------------------------------------
NUWA_MARKER="$HOME/.claude/skills/huashu-nuwa/SKILL.md"

if [ -f "$NUWA_MARKER" ]; then
  echo "nuwa-skill: already installed, skipping"
else
  echo "nuwa-skill: installing..."
  npx -y skills@latest add alchaincyf/nuwa-skill -g -a claude-code -s '*' -y >/dev/null 2>&1 || \
    echo "nuwa-skill: install failed (continuing)"
  if [ -f "$NUWA_MARKER" ]; then
    echo "nuwa-skill: ready"
  fi
fi

# ---------------------------------------------------------------------------
# 3b) darwin-skill (alchaincyf/darwin-skill) — "Darwin Skill 2.0", an autonomous
#     skill optimizer: scores other SKILL.md files on a 9-dim rubric, hill-climbs
#     improvements with git version control + blind judge agents, keeps or
#     reverts based on test results. Marker: its SKILL.md.
# ---------------------------------------------------------------------------
DARWIN_MARKER="$HOME/.claude/skills/darwin-skill/SKILL.md"

if [ -f "$DARWIN_MARKER" ]; then
  echo "darwin-skill: already installed, skipping"
else
  echo "darwin-skill: installing..."
  npx -y skills@latest add alchaincyf/darwin-skill -g -a claude-code -s '*' -y >/dev/null 2>&1 || \
    echo "darwin-skill: install failed (continuing)"
  if [ -f "$DARWIN_MARKER" ]; then
    echo "darwin-skill: ready"
  fi
fi

# ---------------------------------------------------------------------------
# 4) Locally-distilled persona / theme Skills generated by huashu-nuwa. Source
#    of truth is committed in this repo under .claude/skills/<name>; this step
#    mirrors each to the user level so they're globally available across
#    sessions. Re-syncs whenever the repo copy is newer. Add new distilled
#    skills to PERSONA_SKILLS below.
# ---------------------------------------------------------------------------
PERSONA_SKILLS="karpathy-perspective gushen"
SKILLS_ROOT="${CLAUDE_PROJECT_DIR:-$PWD}/.claude/skills"
for sk in $PERSONA_SKILLS; do
  src="$SKILLS_ROOT/$sk"
  dst="$HOME/.claude/skills/$sk"
  [ -f "$src/SKILL.md" ] || continue
  if [ ! -f "$dst/SKILL.md" ] || [ "$src/SKILL.md" -nt "$dst/SKILL.md" ]; then
    echo "$sk: syncing to user level..."
    mkdir -p "$dst"
    cp -R "$src/." "$dst/" 2>/dev/null && echo "$sk: ready"
  else
    echo "$sk: already installed, skipping"
  fi
done

# Persist PATH so plain `agent-memory` resolves in this session's shells.
if [ -n "${CLAUDE_ENV_FILE:-}" ] && [ -w "$(dirname "$CLAUDE_ENV_FILE")" ]; then
  echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$CLAUDE_ENV_FILE"
fi
